version: "3.8"

services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    volumes:
      - client-volume:/app/build
  admin:
    build:
      context: ./admin
      dockerfile: Dockerfile
    volumes:
      - admin-volume:/app/build
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - client-volume:/usr/share/nginx/html
      - admin-volume:/usr/share/nginx/html/admin
      - ./nginx/nginx.conf:/etc/nginx/conf/conf.d/default.conf
    depends_on:
      - client

volumes:
  client-volume:
  admin-volume:
